name: Build ROM
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: 
      name: Builder
      url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Disable git
        run: rm -rf .git

      - name: Build
        run: bash build.sh
        env:
          RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT: ${{ secrets.TG_CHAT }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Logs
          path: |
            *.txt
