name: Build ROM
on:
  workflow_dispatch:
    inputs:
      clean_dir:
        description: 'Specify directories to be removed with spaces. Warning! This runs (rm -rf <dirs>) command. Output directory is cleaned by default.'
        required: false
        default: ''

jobs:
  build:
    runs-on: self-hosted
    environment: 
      name: Builder
    steps:
      - name: Clean Directory
        if: ${{ inputs.clean_dir }}
        run: rm -rf ${{ inputs.clean_dir }}

      - name: Checkout
        run: |
          rm -rf __rom-build_scripts__
          git_branch=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          echo "Branch: $git_branch"
          git clone ${{ github.server_url }}/${{ github.repository }} __rom-build_scripts__ -b $git_branch --depth 1 --single-branch

      - name: Build
        run: (cd __rom-build_scripts__ && bash build.sh)
        env:
          RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT: ${{ secrets.TG_CHAT }}
          GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Logs
          path: |
            *.txt
