name: Build ROM
on:
  workflow_dispatch:
    inputs:
      fresh_install:
        description: 'Do you want to clean everything and start fresh?'
        type: boolean
        required: false
        default: false
      clean_dir:
        description: 'Ignore this if you have set above fresh install. Specify directories to be removed with spaces. Warning! This runs (rm -rf <dirs>) command. Output directory is cleaned by default.'
        required: false
        type: string
        default: ''

jobs:
  build:
    runs-on: self-hosted
    environment: 
      name: Builder
    steps:
      - name: Clean Everything and Start Fresh
        if: ${{ inputs.fresh_install }}
        run: rm -rf *

      - name: Clean Directory
        if: ${{ inputs.clean_dir }}
        run: rm -rf ${{ inputs.clean_dir }}

      - name: Checkout
        run: |
          rm -rf __rom-build_scripts__
          git_branch=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          echo "Branch: $git_branch"
          git clone ${{ github.server_url }}/${{ github.repository }} __rom-build_scripts__ -b $git_branch --depth 1 --single-branch

      - name: Build
        run: |
          rm -rf util.sh build.sh .env
          cp -r __rom-build_scripts__/util.sh .
          cp -r __rom-build_scripts__/build.sh .
          cp -r __rom-build_scripts__/.env .
          chmod +x build.sh
          ./build.sh
        env:
          RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT: ${{ secrets.TG_CHAT }}
          GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Logs
          path: |
            *.txt
