name: Build ROM
on:
  workflow_dispatch:
    inputs:
      clean_dir:
        description: 'Specify directory to be cleaned before build. Output directory is cleaned by default.'
        required: false
        default: ''

jobs:
  build:
    runs-on: self-hosted
    environment: 
      name: Builder
    steps:
      - name: Clean Directory
        if: ${{ inputs.clean_dir }}
        run: rm -rf ${{ inputs.clean_dir }}

      - name: Checkout
        run: git clone ${{ github.server_url }}/${{ github.repository }} __rom-build_scripts__ -b main --depth 1 --single-branch || (cd __rom-build_scripts__ && git pull)

      - name: Build
        run: bash __rom-build_scripts__/build.sh
        env:
          RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT: ${{ secrets.TG_CHAT }}
          GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Logs
          path: |
            *.txt
