name: CI Test and Sync
on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "docs/**"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error

  sync:
    needs: shellcheck
    name: Sync
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      
      - name: Merge changes from main
        run: |
          arr=$(git branch -r | grep -v HEAD | grep -v main | sed 's/origin\///g')
          for i in $arr
          do
            i=$(echo $i | xargs)
            if [[ $i == feature/* ]] || [[ $i == bugfix/* ]]; then
              continue
            fi
            git checkout $i
            git merge main --no-edit --no-ff || echo "Merge failed for $i"
          done
      - name: Push all changes
        run: git push origin --all
