name: Build on VM

on:
  workflow_dispatch:
    inputs:
      fresh_install:
        description: 'Do you want to clean everything and start fresh?. All git repos are updated automatically. Do not check this if a build has failed because of some error, just re run workflow without checking this. This will reduce build time significantly.'
        type: boolean
        required: false
        default: false
      clean_dir:
        description: 'Ignore this if you have set above fresh install. Specify directories to be removed with spaces (if a directory name contains space enlcose with ""). Warning! This runs (rm -rf <dirs>) command. Output directory is cleaned by default.'
        required: false
        type: string
        default: ''

# queue up builds to prevent failures on progress of other builds
concurrency: 
  group: building_vm
  cancel-in-progress: false

jobs:
  start-vm:
    uses: ./.github/workflows/gcp_control_vm.yml
    with:
      action: 'start'
    secrets: inherit

  build:
    needs: start-vm
    if: success()
    uses: ./.github/workflows/build.yml
    with:
      fresh_install: ${{ github.event.inputs.fresh_install == 'true' }}
      clean_dir: ${{ github.event.inputs.clean_dir }}
    secrets: inherit

  stop-vm:
    needs: build
    if: always()
    uses: ./.github/workflows/gcp_control_vm.yml
    with:
      action: 'stop'
    secrets: inherit
