# Test to check bash scripts
name: Test
on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "docs/**"

permissions: {}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
